version: 2.1

executors:
  cmake-executor:
    docker:
      - image: circleci/gcc:latest
    working_directory: ~/project

jobs:
  build:
    executor: cmake-executor
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -y cmake ninja-build xvfb

      - run:
          name: Run Xvfb
          command: |
            Xvfb :99 -screen 0 1920x1080x24 &
            echo "DISPLAY=:99" >> $BASH_ENV
            source $BASH_ENV

      - run:
          name: Install vcpkg
          command: |
            git clone https://github.com/microsoft/vcpkg.git
            cd vcpkg
            ./bootstrap-vcpkg.sh

      - run:
          name: Build
          command: |
            mkdir -p build
            cd build
            cmake .. -G Ninja -DCMAKE_TOOLCHAIN_FILE=../vcpkg/scripts/buildsystems/vcpkg.cmake
            ninja

      - run:
          name: Test
          command: |
            cd build
            ctest --output-on-failure

workflows:
  version: 2
  build:
    jobs:
      - build