version: 2.1

executors:
  ubuntu-cmake-executor:
    docker:
      - image: ubuntu:20.04
    environment:
      DEBIAN_FRONTEND: noninteractive
    working_directory: ~/project

orbs:
  win: circleci/windows@5.0

jobs:
  setup-ubuntu:
    executor: ubuntu-cmake-executor
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            apt-get update
            apt-get install -y build-essential cmake ninja-build xvfb curl zip unzip tar bison git

      - run:
          name: Run Xvfb
          command: |
            Xvfb :99 -screen 0 1920x1080x24 &
            echo "DISPLAY=:99" >> $BASH_ENV
            source $BASH_ENV

      - run:
          name: Install vcpkg
          command: |
            git clone https://github.com/microsoft/vcpkg.git
            cd vcpkg
            ./bootstrap-vcpkg.sh

      - save_cache:
          key: vcpkg-cache-ubuntu
          paths:
            - ~/vcpkg/installed

  setup-windows:
    executor: win/server-2022
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            choco install cmake --installargs '"ADD_CMAKE_TO_PATH=System"' -y
            choco install ninja -y
            choco install git -y

      - run:
          name: Install vcpkg
          command: |
            git clone https://github.com/microsoft/vcpkg.git C:\vcpkg
            cd C:\vcpkg
            .\bootstrap-vcpkg.bat

      - save_cache:
          key: vcpkg-cache-windows
          paths:
            - C:\vcpkg\installed

  build-ubuntu:
    executor: ubuntu-cmake-executor
    steps:
      - checkout
      - restore_cache:
          key: vcpkg-cache-ubuntu
      - run:
          name: Build
          command: |
            mkdir -p build
            cd build
            cmake .. -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=../vcpkg/scripts/buildsystems/vcpkg.cmake
            ninja

      - run:
          name: Test
          command: |
            cd build
            ctest --output-on-failure

  build-windows:
    executor: win/server-2022
    steps:
      - checkout
      - restore_cache:
          key: vcpkg-cache-windows
      - run:
          name: Build
          command: |
            mkdir build
            cd build
            cmake .. -G Ninja -DCMAKE_TOOLCHAIN_FILE=C:\vcpkg\scripts\buildsystems\vcpkg.cmake
            ninja

workflows:
  version: 2
  Ubuntu-20.04:
    jobs:
      - setup-ubuntu
      - build-ubuntu:
          requires:
            - setup-ubuntu

  Windows-2022:
    jobs:
      - setup-windows
      - build-windows:
          requires:
            - setup-windows
