name: CMake CI with vcpkg

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  build:
    name: Build and Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      # Checkout repository
      - name: Checkout source code
        uses: actions/checkout@v3

      # Setup vcpkg
      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgJson: true

      # Configure CMake
      - name: Configure CMake
        run: |
          cmake -S . -B build \
            -DCMAKE_TOOLCHAIN_FILE=${{ steps.vcpkg.outputs.vcpkgRoot }}/scripts/buildsystems/vcpkg.cmake \
            -DCMAKE_BUILD_TYPE=Release

      # Build the project
      - name: Build
        run: cmake --build build --config Release

      # Run tests (if you have tests enabled in your CMake project)
      - name: Run Tests
        run: ctest --test-dir build --output-on-failure
