name: Build

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup CMake
        uses: jwlawson/actions-setup-cmake@v1
        with:
          cmake-version: '3.20.0'

      - name: Set up vcpkg
        uses: microsoft/vcpkg-action@v2
        with:
          vcpkgJson: '${{ github.workspace }}/vcpkg.json'

      - name: Configure CMake
        run: |
          cmake -B build -S . -DCMAKE_TOOLCHAIN_FILE=$VCPKG_ROOT/scripts/buildsystems/vcpkg.cmake

      - name: Build
        run: |
          cmake --build build --config Release